version: '3.8'

services:
  # --- Serveur web NGINX ---
  web:
    build: ./docker/nginx
    container_name: web
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=test.blossom.mei
      - NGINX_PORT=80
    depends_on:
      - wordpress
    networks:
      - backend
      - monitoring

  # --- Base de données MySQL ---
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - backend

  # --- WordPress ---
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app/wordpress:/var/www/html
      - ./config/wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db
    networks:
      - backend
      - monitoring

  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  db:
  wordpress:
  grafana_data:

networks:
  backend:
  monitoring:
