version: '3.8'

services:
  # --- Serveur web NGINX ---
  web:
    image: nginx
    container_name: web
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NGINX_HOST=test.blossom.mei
      - NGINX_PORT=80
    depends_on:
      - wordpress
    networks:
      - monitoring
      - backend

  # --- Base de données MySQL ---
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - backend

  # --- WordPress ---
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app/wordpress:/var/www/html
      - ./config/wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db
    networks:
      - backend
      - monitoring

  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  # --- Node Exporter ---
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  db:
  wordpress:
  prometheus_data:

networks:
  backend:
  monitoring:
