global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # --- Scrape Prometheus ---
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # --- Scrape Node Exporter ---
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
